/// Flutter icons AppBarIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppBarIcons
///      fonts:
///       - asset: fonts/AppBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppBarIcons {
  AppBarIcons._();

  static const _kFontFam = 'AppBarIcons';

  static const IconData right_arrow = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData filters = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe802, fontFamily: _kFontFam);
}
